<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Farukh" failures="2" tests="2" name="edgetest" time="26.652" errors="0" timestamp="2024-12-10T15:45:11 EST">
  <testcase classname="testCases.TC001_AccountRegistrationTest" name="verifyAccountRegistraion" time="11.676">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC001_AccountRegistrationTest.verifyAccountRegistraion(TC001_AccountRegistrationTest.java:55)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyAccountRegistraion -->
  <testcase classname="testCases.TC002_LoginTest" name="verifyLogin" time="20.22">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC002_LoginTest.verifyLogin(TC002_LoginTest.java:34)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- edgetest -->
